ID: 2025Y-12M-11D-09h31m21s_9gCg
PID: 977548
START_DATETIME: 2025-12-11 09:31:21.398833
FILE: /home/ywatanabe/proj/scitex-code/examples/msword/03_save_docx.py
SDIR_OUT: /home/ywatanabe/proj/scitex-code/examples/msword/03_save_docx_out
SDIR_RUN: 
    /home/ywatanabe/proj/scitex-code/examples/msword/03_save_docx_out/RUNNING/2025Y-12M-11D-09h31m21s_9gCg-main
ARGS: {}
EXIT_STATUS: 0
END_DATETIME: 2025-12-11 09:31:37.903382
RUN_DURATION: 00:00:16
