ID: 2025Y-12M-11D-08h58m38s_Q7Zm
PID: 906704
START_DATETIME: 2025-12-11 08:58:38.800090
FILE: /home/ywatanabe/proj/scitex-code/examples/msword/05_extract_content.py
SDIR_OUT: 
    /home/ywatanabe/proj/scitex-code/examples/msword/05_extract_content_out
SDIR_RUN: 
    /home/ywatanabe/proj/scitex-code/examples/msword/05_extract_content_out/RUNNING/2025Y-12M-11D-08h58m38s_Q7Zm-main
ARGS: {}
EXIT_STATUS: 0
END_DATETIME: 2025-12-11 08:58:46.700395
RUN_DURATION: 00:00:07
