ID: 2025Y-11M-19D-14h57m08s_XnmT
PID: 100949
START_DATETIME: 2025-11-19 14:57:08.860473
FILE: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication.py
SDIR_OUT: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication_out
SDIR_RUN: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication_out/RUNNING/2025Y-11M-19D-14h57m08s_XnmT-main
ARGS:
    verbose: true
EXIT_STATUS: 0
END_DATETIME: 2025-11-19 14:57:15.849757
RUN_DURATION: 00:00:06
