ID: 2025Y-11M-19D-14h58m31s_f1WY
PID: 101842
START_DATETIME: 2025-11-19 14:58:31.750315
FILE: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication.py
SDIR_OUT: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication_out
SDIR_RUN: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication_out/RUNNING/2025Y-11M-19D-14h58m31s_f1WY-main
ARGS:
    verbose: true
EXIT_STATUS: 0
END_DATETIME: 2025-11-19 14:58:42.948753
RUN_DURATION: 00:00:11
