ID: 2026Y-03M-04D-19h54m26s_yhn6
PID: 805414
START_DATETIME: 2026-03-04 19:54:26.537570
FILE: 
    /home/ywatanabe/proj/scitex-python/examples/scitex/clew/multi_parent/08_make_figures.py
SDIR_OUT: 
    /home/ywatanabe/proj/scitex-python/examples/scitex/clew/multi_parent/08_make_figures_out
SDIR_RUN: 
    /home/ywatanabe/proj/scitex-python/examples/scitex/clew/multi_parent/08_make_figures_out/RUNNING/2026Y-03M-04D-19h54m26s_yhn6-main
ARGS:
    input_file:
EXIT_STATUS: 0
END_DATETIME: 2026-03-04 19:54:31.744999
RUN_DURATION: 00:00:05
