ID: 2025Y-11M-19D-18h10m57s_bUqa
PID: 260970
START_DATETIME: 2025-11-19 18:10:57.481819
FILE: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication.py
SDIR_OUT: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication_out
SDIR_RUN: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication_out/RUNNING/2025Y-11M-19D-18h10m57s_bUqa-main
ARGS:
    verbose: true
EXIT_STATUS: 0
END_DATETIME: 2025-11-19 18:11:18.474332
RUN_DURATION: 00:00:20
