ID: 2026Y-03M-11D-07h19m19s_YuEX
PID: 48371
START_DATETIME: 2026-03-11 07:19:19.569303
FILE: 
    /home/ywatanabe/proj/scitex-python/examples/bridge/04_stats_to_vis_direct.py
SDIR_OUT: 
    /home/ywatanabe/proj/scitex-python/examples/bridge/04_stats_to_vis_direct_out
SDIR_RUN: 
    /home/ywatanabe/proj/scitex-python/examples/bridge/04_stats_to_vis_direct_out/RUNNING/2026Y-03M-11D-07h19m19s_YuEX-main
ARGS: {}
EXIT_STATUS: 0
END_DATETIME: 2026-03-11 07:19:24.294032
RUN_DURATION: 00:00:04
