ID: 2025Y-11M-19D-14h59m15s_gTG9
PID: 102795
START_DATETIME: 2025-11-19 14:59:15.568836
FILE: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication.py
SDIR_OUT: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication_out
SDIR_RUN: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication_out/RUNNING/2025Y-11M-19D-14h59m15s_gTG9-main
ARGS:
    verbose: true
EXIT_STATUS: 0
END_DATETIME: 2025-11-19 14:59:22.322533
RUN_DURATION: 00:00:06
