DEMO:
    demo:
        xxx: 111
        yyy: 222
capture:
    capture:
        screenshot:
            quality: 85
            monitor_id: 0
            output_dir:
        monitoring:
            interval: 1.0
            quality: 60
            verbose: true
            capture_all: false
        gif:
            duration: 0.5
            optimize: true
            max_frames:
        cache:
            max_size_gb: 1.0
ID: 2025Y-12M-20D-12h55m56s_NmXn
PID: 1307844
START_DATETIME: 2025-12-20 12:55:56.069210
FILE: /home/ywatanabe/proj/scitex-code/examples/scitex/stats/statsz.py
SDIR_OUT: /home/ywatanabe/proj/scitex-code/examples/scitex/stats/statsz_out
SDIR_RUN: 
    /home/ywatanabe/proj/scitex-code/examples/scitex/stats/statsz_out/RUNNING/2025Y-12M-20D-12h55m56s_NmXn-main
ARGS: {}
EXIT_STATUS: 1
END_DATETIME: 2025-12-20 12:55:58.258339
RUN_DURATION: 00:00:02
