DEMO:
    demo:
        xxx: 111
        yyy: 222
capture:
    capture:
        screenshot:
            quality: 85
            monitor_id: 0
            output_dir:
        monitoring:
            interval: 1.0
            quality: 60
            verbose: true
            capture_all: false
        gif:
            duration: 0.5
            optimize: true
            max_frames:
        cache:
            max_size_gb: 1.0
ID: 2025Y-12M-09D-09h24m18s_KZFg
PID: 1567537
START_DATETIME: 2025-12-09 09:24:18.284879
FILE: /home/ywatanabe/proj/scitex-code/examples/bridge/02_add_stats_to_plot.py
SDIR_OUT: 
    /home/ywatanabe/proj/scitex-code/examples/bridge/02_add_stats_to_plot_out
SDIR_RUN: 
    /home/ywatanabe/proj/scitex-code/examples/bridge/02_add_stats_to_plot_out/RUNNING/2025Y-12M-09D-09h24m18s_KZFg-main
ARGS: {}
EXIT_STATUS: 0
END_DATETIME: 2025-12-09 09:24:27.729209
RUN_DURATION: 00:00:09
