ID: 2025Y-11M-19D-18h03m30s_kC13
PID: 255390
START_DATETIME: 2025-11-19 18:03:30.900582
FILE: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication.py
SDIR_OUT: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication_out
SDIR_RUN: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication_out/RUNNING/2025Y-11M-19D-18h03m30s_kC13-main
ARGS:
    verbose: true
EXIT_STATUS: 0
END_DATETIME: 2025-11-19 18:03:52.195124
RUN_DURATION: 00:00:21
