ID: 2025Y-11M-19D-16h56m58s_t9eP
PID: 54181
START_DATETIME: 2025-11-19 16:56:58.062217
FILE: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication_v01-not-all-types.py
SDIR_OUT: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication_v01-not-all-types_out
SDIR_RUN: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication_v01-not-all-types_out/RUNNING/2025Y-11M-19D-16h56m58s_t9eP-main
ARGS:
    verbose: true
EXIT_STATUS: 0
END_DATETIME: 2025-11-19 16:57:05.340860
RUN_DURATION: 00:00:07
