ID: 2025Y-11M-19D-14h47m44s_UXYv
PID: 93158
START_DATETIME: 2025-11-19 14:47:44.525004
FILE: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication.py
SDIR_OUT: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication_out
SDIR_RUN: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication_out/RUNNING/2025Y-11M-19D-14h47m44s_UXYv-main
ARGS:
    verbose: true
EXIT_STATUS: 0
END_DATETIME: 2025-11-19 14:47:51.613344
RUN_DURATION: 00:00:07
