ID: 2025Y-11M-19D-16h10m36s_SsAf
PID: 218494
START_DATETIME: 2025-11-19 16:10:36.325646
FILE: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication.py
SDIR_OUT: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication_out
SDIR_RUN: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication_out/RUNNING/2025Y-11M-19D-16h10m36s_SsAf-main
ARGS:
    verbose: true
EXIT_STATUS: 0
END_DATETIME: 2025-11-19 16:10:45.134177
RUN_DURATION: 00:00:08
