ID: 2025Y-12M-11D-08h30m59s_ek97
PID: 834478
START_DATETIME: 2025-12-11 08:30:59.683632
FILE: /home/ywatanabe/proj/scitex-code/examples/msword/03_save_docx.py
SDIR_OUT: /home/ywatanabe/proj/scitex-code/examples/msword/03_save_docx_out
SDIR_RUN: 
    /home/ywatanabe/proj/scitex-code/examples/msword/03_save_docx_out/RUNNING/2025Y-12M-11D-08h30m59s_ek97-main
ARGS: {}
EXIT_STATUS: 0
END_DATETIME: 2025-12-11 08:31:09.296320
RUN_DURATION: 00:00:09
