ID: 2025Y-11M-19D-15h21m12s_7FTJ
PID: 127327
START_DATETIME: 2025-11-19 15:21:12.262948
FILE: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication.py
SDIR_OUT: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication_out
SDIR_RUN: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication_out/RUNNING/2025Y-11M-19D-15h21m12s_7FTJ-main
ARGS:
    verbose: true
EXIT_STATUS: 0
END_DATETIME: 2025-11-19 15:21:19.119398
RUN_DURATION: 00:00:06
