ID: 2025Y-11M-19D-14h53m37s_nhKE
PID: 98266
START_DATETIME: 2025-11-19 14:53:37.652987
FILE: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication.py
SDIR_OUT: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication_out
SDIR_RUN: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication_out/RUNNING/2025Y-11M-19D-14h53m37s_nhKE-main
ARGS:
    verbose: true
EXIT_STATUS: 0
END_DATETIME: 2025-11-19 14:53:46.323838
RUN_DURATION: 00:00:08
