ID: 2025Y-12M-11D-08h59m08s_VCLA
PID: 907166
START_DATETIME: 2025-12-11 08:59:08.752373
FILE: /home/ywatanabe/proj/scitex-code/examples/msword/06_full_pipeline.py
SDIR_OUT: /home/ywatanabe/proj/scitex-code/examples/msword/06_full_pipeline_out
SDIR_RUN: 
    /home/ywatanabe/proj/scitex-code/examples/msword/06_full_pipeline_out/RUNNING/2025Y-12M-11D-08h59m08s_VCLA-main
ARGS: {}
EXIT_STATUS: 0
END_DATETIME: 2025-12-11 08:59:17.319818
RUN_DURATION: 00:00:08
