ID: 2025Y-11M-19D-17h57m09s_8H99
PID: 249738
START_DATETIME: 2025-11-19 17:57:09.927645
FILE: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication.py
SDIR_OUT: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication_out
SDIR_RUN: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication_out/RUNNING/2025Y-11M-19D-17h57m09s_8H99-main
ARGS:
    verbose: true
EXIT_STATUS: 0
END_DATETIME: 2025-11-19 17:57:35.537505
RUN_DURATION: 00:00:25
