ID: 2025Y-11M-19D-17h36m19s_RQhi
PID: 207203
START_DATETIME: 2025-11-19 17:36:19.391252
FILE: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication.py
SDIR_OUT: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication_out
SDIR_RUN: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication_out/RUNNING/2025Y-11M-19D-17h36m19s_RQhi-main
ARGS:
    verbose: true
EXIT_STATUS: 1
END_DATETIME: 2025-11-19 17:36:26.569374
RUN_DURATION: 00:00:07
