"""Runtime cross-package import gate (auto-generated).

Generated by `scitex-dev ecosystem write-integration-tests`.
Hand edits inside the AUTO-GENERATED block will be overwritten on
regeneration; add hand-written cases below the second sentinel.

This test imports every cross-package module that 'scitex-python' references
in its source tree. Renames or moves in peer standalones (or in the
umbrella's deep-import surface) surface as a hard failure here — not
as a silent ModuleNotFoundError when an end user runs the CLI.
"""

import importlib
import importlib.util

import pytest

# ===== AUTO-GENERATED: cross-package imports =====
CROSS_PACKAGE_IMPORTS = [
    "scitex",
    "scitex._dev",
    "scitex._mcp",
    "scitex._mcp._compat",
    "scitex.audio",
    "scitex.browser.core",
    "scitex.browser.pdf",
    "scitex.browser.pdf._save_as_pdf",
    "scitex.capture",
    "scitex.capture._mcp.handlers",
    "scitex.capture.mcp_server",
    "scitex.clew",
    "scitex.cli",
    "scitex.cli._introspect_advanced",
    "scitex.cli.introspect",
    "scitex.cli.main",
    "scitex.cli.mcp",
    "scitex.cloud",
    "scitex.config",
    "scitex.container",
    "scitex.context",
    "scitex.decorators",
    "scitex.decorators._deprecated",
    "scitex.decorators._numpy_fn",
    "scitex.decorators._wrap",
    "scitex.diagram",
    "scitex.dict",
    "scitex.dsp.utils",
    "scitex.dsp.utils._ensure_3d",
    "scitex.dsp.utils._ensure_even_len",
    "scitex.dsp.utils._zero_pad",
    "scitex.dsp.utils.filter",
    "scitex.events",
    "scitex.gen",
    "scitex.introspect",
    "scitex.introspect._mcp.handlers",
    "scitex.io",
    "scitex.io._metadata",
    "scitex.io.bundle",
    "scitex.logging",
    "scitex.mcp_server",
    "scitex.notebook",
    "scitex.notification",
    "scitex.os",
    "scitex.path",
    "scitex.plt",
    "scitex.repro",
    "scitex.resource",
    "scitex.scholar._mcp.handlers",
    "scitex.scholar._mcp.job_handlers",
    "scitex.scholar.jobs",
    "scitex.scholar.pipelines",
    "scitex.security",
    "scitex.session",
    "scitex.sh",
    "scitex.stats",
    "scitex.stats._mcp.server",
    "scitex.stats._utils",
    "scitex.stats._utils._normalizers",
    "scitex.stats.io",
    "scitex.stats.mcp_server",
    "scitex.str",
    "scitex.template",
    "scitex.template._mcp.handlers",
    "scitex.tex",
    "scitex.torch",
    "scitex.tunnel",
    "scitex.types",
    "scitex.usage",
    "scitex.web",
    "scitex.web.download_images",
    "scitex.writer._verify_tree_structure",
    "scitex_agent_container._mcp.server",
    "scitex_agent_container.cli",
    "scitex_audio._mcp.handlers",
    "scitex_audio._utils",
    "scitex_audio.mcp_server",
    "scitex_audit._format",
    "scitex_clew",
    "scitex_clew._db",
    "scitex_clew._logging",
    "scitex_clew._mcp.tools",
    "scitex_clew._registry",
    "scitex_clew._tracker",
    "scitex_container",
    "scitex_container.apptainer",
    "scitex_dataset",
    "scitex_dataset._cli",
    "scitex_dataset._mcp.server",
    "scitex_dev",
    "scitex_dev._cli",
    "scitex_dev._mcp._server",
    "scitex_dev.cli",
    "scitex_dev.dashboard",
    "scitex_dev.docs",
    "scitex_dev.ecosystem",
    "scitex_dev.search",
    "scitex_dev.skills",
    "scitex_dev.types",
    "scitex_dsp",
    "scitex_genai",
    "scitex_hpc._cli",
    "scitex_io",
    "scitex_io._cli._main",
    "scitex_io._flush",
    "scitex_io._load_modules._bibtex",
    "scitex_io._load_modules._con",
    "scitex_io._load_modules._docx",
    "scitex_io._load_modules._eeg",
    "scitex_io._load_modules._hdf5",
    "scitex_io._load_modules._image",
    "scitex_io._load_modules._joblib",
    "scitex_io._load_modules._json",
    "scitex_io._load_modules._markdown",
    "scitex_io._load_modules._matlab",
    "scitex_io._load_modules._numpy",
    "scitex_io._load_modules._pandas",
    "scitex_io._load_modules._pdf",
    "scitex_io._load_modules._pickle",
    "scitex_io._load_modules._torch",
    "scitex_io._load_modules._txt",
    "scitex_io._load_modules._xml",
    "scitex_io._load_modules._yaml",
    "scitex_io._load_modules._zarr",
    "scitex_io._loading._load_cache",
    "scitex_io._mcp.server",
    "scitex_io._save_modules._bibtex",
    "scitex_io._save_modules._catboost",
    "scitex_io._save_modules._csv",
    "scitex_io._save_modules._excel",
    "scitex_io._save_modules._hdf5",
    "scitex_io._save_modules._html",
    "scitex_io._save_modules._image",
    "scitex_io._save_modules._joblib",
    "scitex_io._save_modules._json",
    "scitex_io._save_modules._listed_dfs_as_csv",
    "scitex_io._save_modules._listed_scalars_as_csv",
    "scitex_io._save_modules._matlab",
    "scitex_io._save_modules._mp4",
    "scitex_io._save_modules._numpy",
    "scitex_io._save_modules._optuna_study_as_csv_and_pngs",
    "scitex_io._save_modules._pickle",
    "scitex_io._save_modules._text",
    "scitex_io._save_modules._torch",
    "scitex_io._save_modules._yaml",
    "scitex_io._save_modules._zarr",
    "scitex_ml",
    "scitex_notification",
    "scitex_notification._backends",
    "scitex_notification._backends._config",
    "scitex_notification._backends._twilio",
    "scitex_notification._mcp.handlers",
    "scitex_ssh",
    "scitex_stats",
    "scitex_stats._server",
    "scitex_stats.auto",
    "scitex_stats.descriptive",
    "scitex_tunnel",
    "scitex_ui._mcp.inspect",
    "scitex_writer",
    "scitex_writer._cli",
    "scitex_writer._dataclasses",
    "scitex_writer._mcp.tools",
]
# ===== END AUTO-GENERATED =====


def _import_or_skip_if_peer_absent(module_name: str):
    """Import ``module_name``; skip ONLY when its DISTRIBUTION is not installed.

    THE SCOPE OF THE SKIP IS THE ENTIRE POINT OF THIS FUNCTION (PS-140).

    The previous implementation caught ``ModuleNotFoundError`` from the FULL
    dotted path and skipped on it. That made the gate unable to fail: a
    renamed or moved submodule -- ``scitex_io._load_cache`` ->
    ``scitex_io._loading._load_cache``, the very incident this file was
    written for -- raises exactly that exception, so the one failure the gate
    exists to catch was swallowed and the run reported GREEN. An absent peer
    and a rename inside an installed peer raise the same exception type, and
    the old code could not tell them apart, so it treated every rename as an
    absence.

    The two ARE distinguishable, by SCOPE rather than by exception type:

      * the ROOT distribution is not installed  -> a legitimately absent peer
        (an optional extra, a marker-gated dependency, a lean install). Skip.
      * the root IS installed and a SUBMODULE of it is missing -> a rename or
        a move. FAIL. That is the gate.

    So the skip is scoped to the root and the full path is hard-imported. Not
    dropping the skip altogether matters just as much: a blanket hard import
    would fail a lean install where the peer is legitimately absent -- a gate
    that cannot PASS, in place of one that cannot FAIL.

    One further absence is legitimate, and recognising it is not a widening of
    the hole: the umbrella's ``scitex.<x>`` shim forwards to a separate
    ``scitex_<x>`` distribution, so ``import scitex.io`` fails with ``No
    module named 'scitex_io'`` while the root ``scitex`` is perfectly present.
    That is the same absent-peer category as the root skip, and it is
    recognised structurally -- the missing name must be a DIFFERENT top-level
    distribution with no importable spec at all. A missing submodule of an
    installed distribution never matches it, which is what keeps a rename
    failing.

    The remaining tolerances below are unrelated to PS-140 and are unchanged:
    torch's global-state re-init collision, the umbrella's helpful "install
    with pip install scitex[...]" ImportError, and a C-extension
    METH_CLASS/METH_STATIC quirk on some CPython builds.
    """
    root = module_name.split(".")[0]

    # Skip on the ROOT -- never on the full dotted path.
    pytest.importorskip(root)

    try:
        return importlib.import_module(module_name)
    except ModuleNotFoundError as exc:
        # MUST be caught before ImportError below (it is a subclass).
        _skip_if_a_different_distribution_is_absent(exc, root, module_name)
        raise
    except RuntimeError as exc:
        if "already has a docstring" in str(exc):
            pytest.skip(
                f"{module_name}: torch global-state re-init collision from a "
                f"sibling test (not an umbrella import bug): {exc}"
            )
        raise
    except ImportError as exc:
        # The umbrella's lazy modules raise a *helpful* ImportError when an
        # OPTIONAL backing peer isn't installed (e.g. `scitex.web...:
        # scitex_web is required for scitex.web. Install with: pip install
        # scitex[web]`). That is an absent optional peer -- the same category
        # as the root skip -- not a rename. Skip on the install-hint
        # signature; propagate anything else.
        msg = str(exc)
        if (
            "pip install scitex[" in msg
            or "is required for" in msg
            or "Install with" in msg
        ):
            pytest.skip(
                f"{module_name}: optional backing peer absent in this "
                f"environment (umbrella raised its install hint): {exc}"
            )
        raise
    except ValueError as exc:
        # Some C-extensions (numba-backed peers) raise this at import on
        # certain CPython builds: a binding-vs-interpreter quirk,
        # environmental -- not an umbrella import bug.
        if "METH_CLASS or METH_STATIC" in str(exc):
            pytest.skip(
                f"{module_name}: C-extension METH_CLASS/STATIC quirk on this "
                f"Python build (environmental): {exc}"
            )
        raise


def _skip_if_a_different_distribution_is_absent(
    exc: ModuleNotFoundError, root: str, module_name: str
) -> None:
    """Skip iff the missing name is ANOTHER top-level distribution, absent.

    Returns (so the caller re-raises and the test FAILS) in every other case,
    which is what makes a rename inside an installed distribution loud. The
    test is deliberately narrow on both counts:

      * the missing top-level name must DIFFER from ``root`` -- a missing
        submodule of the module's own distribution is a rename, never an
        absence;
      * that name must have NO importable spec -- if the distribution is
        installed, the piece that went missing is inside it, which is again a
        rename.
    """
    missing_root = (exc.name or "").split(".")[0]
    if not missing_root or missing_root == root:
        return
    try:
        if importlib.util.find_spec(missing_root) is not None:
            return
    except (ImportError, ValueError):
        # Cannot answer "is it installed?" -- do not treat that as grounds to
        # skip. Silence on an unanswerable question is the permissive pole
        # this whole fix exists to close.
        return
    pytest.skip(
        f"{module_name}: forwards to `{missing_root}`, a separate "
        f"distribution not installed in this environment: {exc}"
    )


#: Declared modules that do not resolve against the peer version this package
#: PINS (``scitex-dev==0.28.0``) -- recorded here rather than skipped away.
#:
#: Found by this gate the moment its skip was scoped to the root: exactly the
#: defect class PS-140 was written for, and invisible until now because the
#: old full-path skip swallowed it. ``src/scitex/`` imports all four
#: (``cli/docs.py``, ``cli/skills.py``, ``cli/mcp.py``, ``_mcp/__init__.py``,
#: ``_mcp/_umbrella_tools.py``), and scitex-dev exposes neither them nor --
#: under the underscored ``scitex_dev._docs`` / ``scitex_dev._skills`` that
#: replaced them -- the symbols those sites import. Verified against the
#: pinned tag itself, so this is not a local version skew: ``git ls-tree
#: v0.28.0 src/scitex_dev/`` lists ``_docs`` and ``_skills`` and no ``docs`` /
#: ``skills`` / ``search`` / ``types``.
#:
#: Where those symbols moved to is NOT unambiguous, so the import sites are
#: left to a separate change rather than guessed at. ``strict=True`` means the
#: day they are corrected this gate FAILS until the entry is deleted -- the
#: record cannot rot into a permanent exemption.
UNRESOLVED_AGAINST_PINNED_PEER = {
    "scitex_dev.docs": "scitex-dev==0.28.0 ships no `docs` (cf. `_docs`)",
    "scitex_dev.search": "scitex-dev==0.28.0 ships no `search`",
    "scitex_dev.skills": "scitex-dev==0.28.0 ships no `skills` (cf. `_skills`)",
    "scitex_dev.types": "scitex-dev==0.28.0 ships no `types`",
}


def _cases():
    for name in CROSS_PACKAGE_IMPORTS:
        reason = UNRESOLVED_AGAINST_PINNED_PEER.get(name)
        if reason is None:
            yield pytest.param(name)
        else:
            yield pytest.param(
                name, marks=pytest.mark.xfail(strict=True, reason=reason)
            )


@pytest.mark.parametrize("module_name", list(_cases()))
def test_cross_package_import(module_name):
    """A declared cross-package module imports cleanly when it is installed."""
    # Arrange: the module name is supplied by the parametrize list above.
    # Act
    mod = _import_or_skip_if_peer_absent(module_name)
    # Assert: import_module returns the loaded module (never None on success).
    assert mod is not None
