ID: 2025Y-11M-19D-17h29m42s_Febn
PID: 164054
START_DATETIME: 2025-11-19 17:29:42.209964
FILE: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication.py
SDIR_OUT: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication_out
SDIR_RUN: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication_out/RUNNING/2025Y-11M-19D-17h29m42s_Febn-main
ARGS:
    verbose: true
EXIT_STATUS: 0
END_DATETIME: 2025-11-19 17:30:07.575268
RUN_DURATION: 00:00:25
