ID: 2025Y-11M-19D-17h33m53s_yC4a
PID: 191714
START_DATETIME: 2025-11-19 17:33:53.686207
FILE: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication.py
SDIR_OUT: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication_out
SDIR_RUN: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication_out/RUNNING/2025Y-11M-19D-17h33m53s_yC4a-main
ARGS:
    verbose: true
EXIT_STATUS: 0
END_DATETIME: 2025-11-19 17:34:22.482093
RUN_DURATION: 00:00:28
