ID: 2025Y-11M-19D-14h51m38s_KfiM
PID: 96951
START_DATETIME: 2025-11-19 14:51:38.250541
FILE: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication.py
SDIR_OUT: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication_out
SDIR_RUN: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication_out/RUNNING/2025Y-11M-19D-14h51m38s_KfiM-main
ARGS:
    verbose: true
EXIT_STATUS: 0
END_DATETIME: 2025-11-19 14:51:47.263448
RUN_DURATION: 00:00:09
