ID: 2025Y-11M-19D-17h35m13s_duWz
PID: 197307
START_DATETIME: 2025-11-19 17:35:13.433823
FILE: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication.py
SDIR_OUT: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication_out
SDIR_RUN: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication_out/RUNNING/2025Y-11M-19D-17h35m13s_duWz-main
ARGS:
    verbose: true
EXIT_STATUS: 0
END_DATETIME: 2025-11-19 17:35:54.852928
RUN_DURATION: 00:00:41
