ID: 2026Y-03M-03D-21h31m56s_yMgI
PID: 6327
START_DATETIME: 2026-03-03 21:31:56.892254
FILE: /scitex-python/examples/scitex/clew/01_source_a.py
SDIR_OUT: /scitex-python/examples/scitex/clew/01_source_a_out
SDIR_RUN: 
    /scitex-python/examples/scitex/clew/01_source_a_out/RUNNING/2026Y-03M-03D-21h31m56s_yMgI-main
ARGS:
    n_samples: 200
EXIT_STATUS: 0
END_DATETIME: 2026-03-03 21:32:33.194171
RUN_DURATION: 00:00:36
