ID: 2025Y-11M-19D-17h32m54s_nUfA
PID: 183407
START_DATETIME: 2025-11-19 17:32:54.981908
FILE: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication.py
SDIR_OUT: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication_out
SDIR_RUN: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication_out/RUNNING/2025Y-11M-19D-17h32m54s_nUfA-main
ARGS:
    verbose: true
EXIT_STATUS: 0
END_DATETIME: 2025-11-19 17:33:31.605981
RUN_DURATION: 00:00:36
