ID: 2026Y-03M-11D-07h19m58s_RbWN
PID: 52190
START_DATETIME: 2026-03-11 07:19:58.690932
FILE: /home/ywatanabe/proj/scitex-python/examples/demo_figures/01_scitex_plt.py
SDIR_OUT: 
    /home/ywatanabe/proj/scitex-python/examples/demo_figures/01_scitex_plt_out
SDIR_RUN: 
    /home/ywatanabe/proj/scitex-python/examples/demo_figures/01_scitex_plt_out/RUNNING/2026Y-03M-11D-07h19m58s_RbWN-demo_line_plot
ARGS: {}
EXIT_STATUS: 0
END_DATETIME: 2026-03-11 07:20:06.556243
RUN_DURATION: 00:00:07
