ID: 2025Y-11M-19D-15h26m44s_ZzrR
PID: 132439
START_DATETIME: 2025-11-19 15:26:44.164707
FILE: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication.py
SDIR_OUT: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication_out
SDIR_RUN: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication_out/RUNNING/2025Y-11M-19D-15h26m44s_ZzrR-main
ARGS:
    verbose: true
EXIT_STATUS: 0
END_DATETIME: 2025-11-19 15:26:52.006999
RUN_DURATION: 00:00:07
