ID: 2025Y-11M-19D-16h08m18s_wb8c
PID: 212378
START_DATETIME: 2025-11-19 16:08:18.498606
FILE: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication.py
SDIR_OUT: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication_out
SDIR_RUN: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication_out/RUNNING/2025Y-11M-19D-16h08m18s_wb8c-main
ARGS:
    verbose: true
EXIT_STATUS: 0
END_DATETIME: 2025-11-19 16:08:27.798185
RUN_DURATION: 00:00:09
