ID: 2026Y-03M-11D-07h18m25s_YDUF
PID: 42418
START_DATETIME: 2026-03-11 07:18:25.472769
FILE: /home/ywatanabe/proj/scitex-python/examples/bridge/02_add_stats_to_plot.py
SDIR_OUT: 
    /home/ywatanabe/proj/scitex-python/examples/bridge/02_add_stats_to_plot_out
SDIR_RUN: 
    /home/ywatanabe/proj/scitex-python/examples/bridge/02_add_stats_to_plot_out/RUNNING/2026Y-03M-11D-07h18m25s_YDUF-main
ARGS: {}
EXIT_STATUS: 1
END_DATETIME: 2026-03-11 07:18:32.246386
RUN_DURATION: 00:00:06
