ID: 2025Y-11M-19D-17h32m34s_ZHzv
PID: 181631
START_DATETIME: 2025-11-19 17:32:34.027050
FILE: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication.py
SDIR_OUT: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication_out
SDIR_RUN: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication_out/RUNNING/2025Y-11M-19D-17h32m34s_ZHzv-main
ARGS:
    verbose: true
EXIT_STATUS: 0
END_DATETIME: 2025-11-19 17:32:40.693151
RUN_DURATION: 00:00:06
