ID: 2025Y-11M-19D-14h56m42s_uUkM
PID: 100447
START_DATETIME: 2025-11-19 14:56:42.302333
FILE: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication.py
SDIR_OUT: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication_out
SDIR_RUN: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication_out/RUNNING/2025Y-11M-19D-14h56m42s_uUkM-main
ARGS:
    verbose: true
EXIT_STATUS: 0
END_DATETIME: 2025-11-19 14:56:49.379269
RUN_DURATION: 00:00:07
