ID: 2025Y-11M-19D-16h09m03s_bjHF
PID: 212868
START_DATETIME: 2025-11-19 16:09:03.617826
FILE: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication.py
SDIR_OUT: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication_out
SDIR_RUN: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication_out/RUNNING/2025Y-11M-19D-16h09m03s_bjHF-main
ARGS:
    verbose: true
EXIT_STATUS: 0
END_DATETIME: 2025-11-19 16:09:12.757175
RUN_DURATION: 00:00:09
