ID: 2025Y-11M-19D-18h14m50s_aksC
PID: 263420
START_DATETIME: 2025-11-19 18:14:50.180528
FILE: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication.py
SDIR_OUT: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication_out
SDIR_RUN: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication_out/RUNNING/2025Y-11M-19D-18h14m50s_aksC-main
ARGS:
    verbose: true
EXIT_STATUS: 0
END_DATETIME: 2025-11-19 18:15:14.400390
RUN_DURATION: 00:00:24
