#!/usr/bin/env python3.11
"""Audit line counts per file against the SciTeX per-extension limits (#95).

Limits:
    .py, .sh, .el, .ts, .tsx, .js, .jsx, .css, .md   → 512
    .html, .htm                                       → 1024

Skips auto-generated output (Sphinx HTML under _sphinx_html/, __pycache__,
git hooks, node_modules).

Ships with a grandfathered allow-list so the repo can adopt the limit
without rewriting 180+ legacy files first. New files over the limit
fail CI.

Exit 0 on clean; 1 if any NEW over-limit file is found.

Usage:
    python3.11 scripts/audit_line_limits.py [--root src,tests]
    python3.11 scripts/audit_line_limits.py --update-allowlist
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

LIMITS = {
    ".py": 512,
    ".sh": 512,
    ".el": 512,
    ".ts": 512,
    ".tsx": 512,
    ".js": 512,
    ".jsx": 512,
    ".css": 512,
    ".md": 512,
    ".html": 1024,
    ".htm": 1024,
}

SKIP_DIR_MARKERS = {
    "__pycache__",
    "_sphinx_html",
    "node_modules",
    ".git",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
}

ALLOWLIST = Path(__file__).parent / "line_limits_allowlist.txt"


def count_lines(path: Path) -> int:
    try:
        with path.open(errors="ignore") as f:
            return sum(1 for _ in f)
    except OSError:
        return 0


def scan(roots: list[Path]) -> list[tuple[int, int, Path]]:
    """Return [(lines, cap, path), ...] for files over their cap."""
    over: list[tuple[int, int, Path]] = []
    for root in roots:
        if not root.exists():
            continue
        for p in root.rglob("*"):
            if not p.is_file():
                continue
            if any(part in SKIP_DIR_MARKERS for part in p.parts):
                continue
            cap = LIMITS.get(p.suffix)
            if cap is None:
                continue
            n = count_lines(p)
            if n > cap:
                over.append((n, cap, p))
    return sorted(over, reverse=True)


def load_allowlist(repo_root: Path) -> set[str]:
    if not ALLOWLIST.exists():
        return set()
    return {
        line.strip()
        for line in ALLOWLIST.read_text().splitlines()
        if line.strip() and not line.startswith("#")
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root",
        default="src,tests",
        help="Comma-separated top-level dirs to scan (default: src,tests)",
    )
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=Path(__file__).parent.parent,
        help="Repo root (default: parent of scripts/)",
    )
    parser.add_argument(
        "--update-allowlist",
        action="store_true",
        help="Rewrite scripts/line_limits_allowlist.txt with the current over-limit file set. Use once per grandfathering event; review the diff before committing.",
    )
    args = parser.parse_args()

    repo_root: Path = args.repo_root.resolve()
    roots = [repo_root / d for d in args.root.split(",") if d]
    over = scan(roots)

    if args.update_allowlist:
        ALLOWLIST.write_text(
            "# Auto-generated by audit_line_limits.py --update-allowlist.\n"
            "# Files here are grandfathered into the #95 line-limit rule.\n"
            "# Each over-limit file is a candidate for refactor; see #97 etc.\n\n"
            + "\n".join(str(p.relative_to(repo_root)) for _, _, p in over)
            + "\n"
        )
        print(f"Wrote {len(over)} grandfathered paths to {ALLOWLIST}")
        return 0

    allowed = load_allowlist(repo_root)
    grandfathered = [x for x in over if str(x[2].relative_to(repo_root)) in allowed]
    new_violations = [
        x for x in over if str(x[2].relative_to(repo_root)) not in allowed
    ]

    print(
        f"{len(over)} total over-limit files "
        f"({len(grandfathered)} grandfathered, "
        f"{len(new_violations)} NEW)"
    )

    if new_violations:
        print("\nNEW violations (CI-blocking):")
        for n, cap, p in new_violations[:20]:
            rel = p.relative_to(repo_root)
            print(f"  {n:>5} (cap {cap}) {rel}")
        print(
            "\nFAIL — split these files before merging, or run "
            "`--update-allowlist` if you are intentionally grandfathering."
        )
        return 1

    print("\nPASS — no new over-limit files.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
