ID: 2025Y-11M-19D-15h18m32s_3FKg
PID: 125700
START_DATETIME: 2025-11-19 15:18:32.350951
FILE: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication.py
SDIR_OUT: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication_out
SDIR_RUN: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication_out/RUNNING/2025Y-11M-19D-15h18m32s_3FKg-main
ARGS:
    verbose: true
EXIT_STATUS: 0
END_DATETIME: 2025-11-19 15:18:40.397721
RUN_DURATION: 00:00:08
