ID: 2026Y-03M-11D-07h18m56s_K9yJ
PID: 46943
START_DATETIME: 2026-03-11 07:18:56.675432
FILE: /home/ywatanabe/proj/scitex-python/examples/bridge/03_unified_workflow.py
SDIR_OUT: 
    /home/ywatanabe/proj/scitex-python/examples/bridge/03_unified_workflow_out
SDIR_RUN: 
    /home/ywatanabe/proj/scitex-python/examples/bridge/03_unified_workflow_out/RUNNING/2026Y-03M-11D-07h18m56s_K9yJ-main
ARGS: {}
EXIT_STATUS: 1
END_DATETIME: 2026-03-11 07:18:56.956953
RUN_DURATION: 00:00:00
