ID: 2025Y-12M-11D-08h33m11s_n6yD
PID: 840074
START_DATETIME: 2025-12-11 08:33:11.257584
FILE: /home/ywatanabe/proj/scitex-code/examples/msword/05_extract_content.py
SDIR_OUT: 
    /home/ywatanabe/proj/scitex-code/examples/msword/05_extract_content_out
SDIR_RUN: 
    /home/ywatanabe/proj/scitex-code/examples/msword/05_extract_content_out/RUNNING/2025Y-12M-11D-08h33m11s_n6yD-main
ARGS: {}
EXIT_STATUS: 0
END_DATETIME: 2025-12-11 08:33:18.049381
RUN_DURATION: 00:00:06
