ID: 2025Y-12M-11D-09h31m57s_2JZs
PID: 978279
START_DATETIME: 2025-12-11 09:31:57.416992
FILE: /home/ywatanabe/proj/scitex-code/examples/msword/05_extract_content.py
SDIR_OUT: 
    /home/ywatanabe/proj/scitex-code/examples/msword/05_extract_content_out
SDIR_RUN: 
    /home/ywatanabe/proj/scitex-code/examples/msword/05_extract_content_out/RUNNING/2025Y-12M-11D-09h31m57s_2JZs-main
ARGS: {}
EXIT_STATUS: 0
END_DATETIME: 2025-12-11 09:32:08.454856
RUN_DURATION: 00:00:11
