ID: 2026Y-03M-18D-16h25m48s_MwYb
PID: 1293979
START_DATETIME: 2026-03-18 16:25:48.420773
FILE: /home/ywatanabe/proj/scitex-python/examples/01_session.py
SDIR_OUT: /home/ywatanabe/proj/scitex-python/examples/01_session_out
SDIR_RUN: 
    /home/ywatanabe/proj/scitex-python/examples/01_session_out/RUNNING/2026Y-03M-18D-16h25m48s_MwYb-main
ARGS:
    data_path: ./data.csv
    n_samples: 50
    learning_rate: 0.001
EXIT_STATUS: 0
END_DATETIME: 2026-03-18 16:25:56.248454
RUN_DURATION: 00:00:07
