ID: 2025Y-11M-19D-18h10m07s_Wqj8
PID: 260310
START_DATETIME: 2025-11-19 18:10:07.782646
FILE: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication.py
SDIR_OUT: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication_out
SDIR_RUN: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication_out/RUNNING/2025Y-11M-19D-18h10m07s_Wqj8-main
ARGS:
    verbose: true
EXIT_STATUS: 0
END_DATETIME: 2025-11-19 18:10:28.745413
RUN_DURATION: 00:00:20
