ID: 2025Y-11M-19D-18h04m56s_mxD6
PID: 256384
START_DATETIME: 2025-11-19 18:04:56.059471
FILE: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication.py
SDIR_OUT: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication_out
SDIR_RUN: 
    /home/ywatanabe/proj/scitex-code/examples/demo_plot_all_types_publication_out/RUNNING/2025Y-11M-19D-18h04m56s_mxD6-main
ARGS:
    verbose: true
EXIT_STATUS: 0
END_DATETIME: 2025-11-19 18:05:22.965737
RUN_DURATION: 00:00:26
